Braintree_Payment_Example/Controllers/BookController.cs
using Braintree;
using Braintree_Payment_Example.Data.Models;
using Braintree_Payment_Example.Data.Services;
using Braintree_Payment_Example.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Transactions;

namespace Braintree_Payment_Example.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _service;

        public BookController(IBookService service)
        {
            _service = service;
        }

        // GET: Books
        public IActionResult Index()
        {
            var items = _service.GetAll();
            return View(items);
        }

        // GET: Books/Details/5
        public IActionResult Details(Guid id)
        {
            var book = _service.GetById(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

    }

   
}

Braintree_Payment_Example/Controllers/CheckoutController.cs
using Braintree;
using Braintree_Payment_Example.Data.Services;
using Braintree_Payment_Example.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Braintree_Payment_Example.Controllers
{

    public class CheckoutController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IBraintreeService _braintreeService;

        public CheckoutController(IBookService courseService, IBraintreeService braintreeService)
        {
            _bookService = courseService;
            _braintreeService = braintreeService;
        }

        public IActionResult Purchase(Guid id)
        {

            var book = _bookService.GetById(id);
            if (book == null) return NotFound();

            var gateway = _braintreeService.GetGateway();
            var clientToken = gateway.ClientToken.Generate();
            ViewBag.ClientToken = clientToken;

            var data = new BookPurchaseVM
            {
                Id = book.Id,
                Description = book.Description,
                Author = book.Author,
                Title = book.Title,
                Price = book.Price,
                Nonce = ""
            };

            return View(data);
        }

        public IActionResult Create(BookPurchaseVM model)
        {
            var gateway = _braintreeService.GetGateway();
            var book = _bookService.GetById(model.Id);

            var request = new TransactionRequest
            {
                Amount = Convert.ToDecimal(book.Price),
                PaymentMethodNonce = model.Nonce,
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
            };

            Result<Transaction> result = gateway.Transaction.Sale(request);

            if (result.IsSuccess())
            {
                return View("Success");
            }
            else
            {
                return View("Failure");
            }
        }
    }
}

Braintree_Payment_Example/Controllers/HomeController.cs
using Braintree_Payment_Example.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Braintree_Payment_Example.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Braintree_Payment_Example/Views/Book/Details.cshtml
@model Braintree_Payment_Example.Data.Models.Book

@{
    ViewData["Title"] = "Details";
}


<div class="card">
    <div class="card-body">
        <h5 class="card-title">@Model.Title <small class="text-muted">(by: @Model.Author</small>)</h5>
        <p class="card-text">@Model.Description</p>
    </div>
    
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Braintree_Payment_Example/Views/Book/Index.cshtml
@model IEnumerable<Braintree_Payment_Example.Data.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-6 col-xs-6" style="padding-bottom: 35px;">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@item.Title <small class="text-muted">(by: @item.Author) </small></h5><br />
                    <p class="card-text">@item.Description</p>
                    @Html.ActionLink("Show details", "Details", "Book", new { id = item.Id })
                    @Html.ActionLink("Purchase - $" +item.Price, "Purchase", "Checkout", new { id = item.Id }, new { @class = "btn btn-success pull-right" })
                </div>
            </div>
        </div>
    }
</div>

Braintree_Payment_Example/Views/Book/Subscribe.cshtml
@{
    ViewData["Title"] = "Subscribe";
}

<h1>CONGRATULATIONS - YOU WERE SUBSCRIBED TO THE PLAN!</h1>

Braintree_Payment_Example/Views/Checkout/Failure.cshtml
@{
    ViewData["Title"] = "Failure";
}

<h1 class="text-center text-danger">Your payment failed!</h1>

Braintree_Payment_Example/Views/Checkout/Purchase.cshtml
@model Braintree_Payment_Example.Data.ViewModels.BookPurchaseVM

@{
    ViewData["Title"] = "Purchase";
}

<div class="wrapper">
    <div class="checkout container">
        <form id="payment-form" method="post" asp-controller="Checkout" asp-action="Create">
            @Html.HiddenFor(n => n.Id)
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title" name="Title" asp-for="@Model.Title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text"><small class="text-muted">Author: @Model.Author</small></p>
                    <p class="card-text"><small class="text-muted">Price: @Model.Price</small></p>
                </div>
               
            </div>
            <section>
                <div class="bt-drop-in-wrapper">
                    <div id="bt-dropin"></div>
                </div>
            </section>
            @Html.HiddenFor(n => n.Nonce, new { @id = "nonce"})
            <hr />
            <button class="btn btn-success" type="submit"><span>Confirm payment - $@Model.Price</span></button>
        </form>
    </div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.22.0/js/dropin.min.js"></script>
<script>
    var client_token = "@ViewBag.ClientToken";
    var form = document.querySelector('#payment-form');

    braintree.dropin.create({
        authorization: client_token,
        container: '#bt-dropin'
    }, function (createErr, instance) {
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            instance.requestPaymentMethod(function (err, payload) {
                if (err) {
                    return;
                }
                document.querySelector('#nonce').value = payload.nonce;
                form.submit();
            });
        });
    });
</script>

Braintree_Payment_Example/Views/Checkout/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h1 class="text-center text-success">Your payment was successful!</h1>

Braintree_Payment_Example/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Braintree_Payment_Example/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Braintree_Payment_Example</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Braintree_Payment_Example.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Braintree_Payment_Example</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Braintree_Payment_Example - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>